### ISSUE TITLE
Implementation of a TryFind function?

### ISSUE THREAD

**Issue by Hansaplast** [sysrpl/JsonTools#14]
When using TJsonNode.Find() I every now and then an exception when the field or path doesn't exist (which makes sense). The data providers that provide the JSON data sometimes leave out fields. 

Would it be an idea to implement a function "TryFind"?

(Which either returns the found TJSONNode or NIL)

**Comment by Hansaplast** [comment]
p.s. I do love how JSONTools works (super easy to work with compared to others), and it performs excellent.

**Comment by Hansaplast** [comment]
FYI: This happens when a path does not seem to exist. 
eg. 
`some/path/to/field` where for example `some` or `path` is null.

I tried encapsulating the Find function (try..except..) but that doesn't seem to work (Access Violation).

**Comment by Hansaplast** [comment]
Something like this (works only for strings of course) ?

```
function JSONTryFind(Node:TJsonNode; FindWhat:string; DefaultValue:string=''): string;
begin
  if Node.Find(FindWhat)=nil then
    Result := DefaultValue
  else
    Result := Node.Find(FindWhat).value;
end;
```

**Comment by sysrpl** [comment]
I've added an overload to Find:

function TJsonNode.Find(const Path: string; out Node: TJsonNode): Boolean;

This is not quite the same as what you suggested, but `out Node` might not be a string, so I think this is the best compromise.
