### ISSUE TITLE
single quote text parse accept

### ISSUE THREAD

**Issue by Awkward-im** [sysrpl/JsonTools#16]
if i trying to pase text '[''babylon'', {"Text":"\u0417\u0432\u0435\u0437\u0434"}, 200, null, null,]' i got error coz (babylon) word rounded by single quotes. but last empty array element parsed without errors. flc-json components of FPC works by reverse way: they accepts single-quoted text but crashes on last empty element.
my temporal patch for NextToken function:
```
  if (C^ = '"') or (C^ = '''') then
  begin
    lC:=C^;
    repeat
      Inc(C);
      if C^ = '\' then
      begin
        Inc(C);
        if C^ = lC then
          Inc(C)
        else if C^ = 'u' then
          if not ((C[1] in Hex) and (C[2] in Hex) and (C[3] in Hex) and (C[4] in Hex)) then
          begin
            T.Tail := C;
            T.Kind := tkError;
            Exit(False);
          end;
      end;
    until C^ in [#0, #10, #13, lC];
    if C^ = lC then
    begin
      Inc(C);
      T.Tail := C;
      T.Kind := tkString;
      Exit(True);
    end;
    T.Tail := C;
    T.Kind := tkError;
    Exit(False);
  end;
```
of course, added at function start:
var
  lC:Char;

**Comment by sysrpl** [comment]
I don't know what this is:

[''babylon'', {"Text":"\u0417\u0432\u0435\u0437\u0434"}, 200, null, null,]

But it's not valid json.
