### ISSUE TITLE
Title of project

### ISSUE THREAD

**Issue by Alexey-T** [sysrpl/JsonTools#2]
Better to have title without space `JsonTools` so google can find it (I tried to find JsonTools but cannot). replace in comments, in repo description, in txt.

**Comment by Alexey-T** [comment]
Maybe JsonTools is trivial. so better to have "JsonSys" or "JsonFast" maybe.

**Comment by Alexey-T** [comment]
“JsonWorker”, “JsonHandler”

**Comment by sysrpl** [comment]
I edited the README.md to JsonTools. Will that suffice?

BTW, google search for "jsontools pascal"
