### ISSUE TITLE
GetAsXX method

### ISSUE THREAD

**Issue by kjteng** [sysrpl/JsonTools#22]
The getAsXXXtype methods (XXX=datatype) automatically clear a node and replace it with a new node if the Kind property requested is not the same as the one in the json data. For example, say node x contains ["1", "123"], then  x.Chld(1).AsNumber wil return 0 and the array changed automatically to ["1", 0].  As I prefer x.child(1).AsNumber method to return 123 without changing the original data (similar to Fields{n].Asfloat method), I have modified the source as appended below. 
I wish to seek your advice on whether the modification will caused any issue on other part of this object. Thank you.
{$DEFINE MODIFIED}
...
function TJsonNode.GetAsNumber: Double;
begin
  if FParent = nil then
    Error(SRootNodeKind);
{$IFDEF MODIFIED}
  if FKind <> nkNumber then
       Result := StrToFloatDef(JsonStringDecode(FValue), 0)   
  else
    Result := StrToFloatDef(FValue, 0);
{$ELSE}
  if FKind <> nkNumber then
  begin
    Clear;
    FKind := nkNumber;
    FValue := '0';
    Exit(0);
  end;
  Result := StrToFloatDef(FValue, 0);
{$ENDIF }
end;

**Comment by sysrpl** [comment]
That is intended. If you change the node type its contents are deleted.

**Comment by sysrpl** [comment]
This is intended. If you change the node type, this its contents will be removed and overwritten with either the new value or the default value for that new type.
