### ISSUE TITLE
Method names for to-string

### ISSUE THREAD

**Issue by Alexey-T** [sysrpl/JsonTools#3]
Current names: AsJson, Value.
Not intuitive.
Not easy to find in IDE.
I suggest:

- AsStringFormatted for formatted str
- AsStringCompact for compact str

**Comment by sysrpl** [comment]
I want to keep the Node.Value property, as it s meant to convey that all Json is text, and Node.Value represents the text under the node. If I keep Node.Value, and still recognizing the need to strip away spacing and linefeeds for more compact storage it would need a different name.

As such  seems as good and any property name, or it could be changed to a read only method: Compact: string; I am unsure if that is any more clear. When it comes down to it, it's only one method name 'AsJson' and the comment describe ti will enough as is. Keeping it at 'AsJson' for now.
