### ISSUE TITLE
HexChars

### ISSUE THREAD

**Issue by Alexey-T** [sysrpl/JsonTools#7]
HexChars: PChar = '0123456789ABCDEF';

what about lowercase hex digits?

**Comment by sysrpl** [comment]
The line you posted is only used when converting from a Pascal string to a Json string. In that case what does it matter that 'Hello'#10'World' is converted to "Hello\u000AWorld" vs "Hello\u000aWorld"?

It makes none.

Meanwhile converting from the Json string of either "Hello\u000AWorld" or "Hello\u000aWorld" will both convert to 'Hello'#10'World' correctly.
