### ISSUE TITLE
Optimize \uNNNN parse

### ISSUE THREAD

**Issue by Alexey-T** [sysrpl/JsonTools#8]
J := UnicodeToSize(StrToInt('$' + C[1] + C[2] + C[3] + C[4]));

maybe can be faster.  Without using StrToInt.

**Comment by Alexey-T** [comment]
You can write -inline- function HexCharToByte, call it 4 times, put 4 bytes to all LongInt bytes.

**Comment by sysrpl** [comment]
That bit of code is only invoked under these conditions:

1) you are accessing a child node of string type
2) the underlying string encoding a chart using "\uHHHH" inside of it
3) you are requesting to convert that to a pascal string

That said, I am unsure to what degree IntToStr is inefficient.

**Comment by Alexey-T** [comment]
What if I have big Unicode strings in big number? It will be inefficient

**Comment by sysrpl** [comment]
Please quantify it.

**Comment by sysrpl** [comment]
Okay, just for you I wrote and inlined more efficient hex conversion functions.
